---
dist: xenial

install:
  - wget -O /tmp/hugo.deb https://github.com/gohugoio/hugo/releases/download/v0.55.4/hugo_extended_0.55.4_Linux-64bit.deb
  - sudo dpkg -i /tmp/hugo.deb
  - git submodule update --init --recursive

script:
  - hugo

deploy:
  - provider: script
    script: bash deploy.sh
    skip_cleanup: true
    on:
      branch: master # or master if you are using the two-repository approach